config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  resources :users
  resources :user_sessions
  resources :packs do
    resources :cards
  end
  resource :review
  get "login", to: "user_sessions#new"
  get "logout", to: "user_sessions#destroy"
  get "signup", to: "users#new"
  match "oauth/callback", to: "oauths#callback", via: [:get, :post]
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  post "set_current_pack", to: "packs#set_current_pack"
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :original_text, :translated_text, presence: true
  validates :pack_id, presence: true
  validate :fields_are_not_equal
  validates :original_text, uniqueness: { scope: :pack_id }

  belongs_to :pack, required: true
  belongs_to :user

  before_create :set_review_date

  mount_uploader :image, ImageUploader

  scope :actual, -> { where("review_date <= ?", Time.now).order("RANDOM()") }

  def correct_answer(answer, answer_time)
    SuperMemo.new(self, answer_time, right_answer?(answer)).call
  end

  private

  def right_answer?(answer)
    Levenshtein.distance(sanitize(translated_text), sanitize(answer)) <= 2
  end

  def set_review_date
    self.review_date = Time.now
  end

  def fields_are_not_equal
    if self.original_text == self.translated_text
      errors.add(:base, "Original and translated text cannot be equal.")
    end
  end

  def sanitize(word)
    word.mb_chars.downcase.strip.to_s
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/pack.rb
class Pack < ActiveRecord::Base
  validates :title, :user_id, presence: true
  validates :title, uniqueness: { scope: :user_id }

  has_many :cards, dependent: :destroy
  belongs_to :user, required: true

  mount_uploader :image, ImageUploader

  before_destroy :reset_current_pack

  def current?
    user.current_pack == self
  end

  def reset_current_pack
    if current?
      user.update_attribute(:current_pack_id, nil)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :password, length: { minimum: 6 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :authentications, dependent: :destroy
  has_many :packs, dependent: :destroy
  has_many :cards, through: :packs
  belongs_to :current_pack, class_name: "Pack"

  authenticates_with_sorcery!
  accepts_nested_attributes_for :authentications

  def card_for_review
    if current_pack
      current_pack.cards.actual.first
    else
      cards.actual.first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  protect_from_forgery with: :exception
  private
    def not_authenticated
      flash[:notice] = "Авторизуйтесь"
      redirect_to login_path
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :find_pack
  before_action :find_card, only: [:edit, :show, :update, :destroy]

  def index
    @cards = @pack.cards
  end

  def show
  end

  def new
    @card = @pack.cards.new
  end

  def create
    @card = @pack.cards.build(card_params)
    if @card.save
      flash[:success] = "Карта успешно создана"
      redirect_to [@pack, @card]
    else
      render :new
    end
  end

  def update
    if @card.update_attributes(card_params)
      flash[:success] = "Карта обновлена"
      redirect_to [@pack, @card]
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @card.destroy
    flash[:success] = "Карта удалена"
    redirect_to pack_cards_path
  end

  private

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :image)
  end

  def find_pack
    @pack = current_user.packs.find(params[:pack_id])
  end

  def find_card
    @card = @pack.cards.find(params[:id])
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login, only: [:oauth, :callback, :destroy]

  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]
    if @user = login_from(provider)
      flash[:notice] = "Авторизован через #{provider.titleize}"
    else
      begin
        @user = create_from(provider)
        reset_session
        auto_login(@user)
        flash[:notice] = "Авторизован через #{provider.titleize}!"
      rescue
        flash[:notice] = "Неудачная авторизация через #{provider.titleize}!"
      end
    end
    redirect_to root_path
  end

  def destroy
    authentication = current_user.authentications.find_by_provider(auth_params)
    if authentication.present?
      authentication.destroy
      flash[:notice] = "Вы успешно вышли из #{provider.titleize} аккаунта."
    else
      flash[:notice] = "Вы не авторизованы через #{provider.titleize} аккаунт."
    end
    redirect_to root_path
  end
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  before_action :find_pack, only: [:edit, :show, :update, :destroy]

  def index
    @packs = current_user.packs
  end

  def show
  end

  def new
    @pack = current_user.packs.new
  end

  def create
    @pack = current_user.packs.build(pack_params)
    if @pack.save
      flash[:success] = "Колода успешно создана"
      redirect_to @pack
    else
      render :new
    end
  end

  def update
    if @pack.update_attributes(pack_params)
      flash[:success] = "Колода обновлена"
      redirect_to @pack
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @pack.destroy
    flash[:success] = "Колода удалена"
    redirect_to packs_url
  end

  def set_current_pack
    if current_user.update_attribute(:current_pack_id, params[:pack_id])
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def pack_params
    params.require(:pack).permit(:title, :image)
  end

  def find_pack
    @pack = current_user.packs.find(params[:id])
  end
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  def review_card
    @card = current_user.cards.find(params[:card_id])
    if @card.correct_answer(params[:translated_text], params[:answer_time])
      flash.now[:success] = "Правильно"
    else
      flash.now[:fail] = "Не правильно"
    end
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    card = current_user.cards.find(card_id)
    if card.correct_answer(params[:translated_text], params[:answer_time])
      flash.now[:success] = "Правильно"
    else
      flash.now[:fail] = "Не правильно"
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def card_id
    params.require(:card_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: [:home]

  def home
    @card = current_user.card_for_review if current_user
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: :destroy

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember_me])
      flash[:success] = "Добро пожаловать"
      redirect_back_or_to root_path
    else
      flash.now[:fail] = "Ошибка, неверный логин или пароль"
      render :new
    end
  end

  def destroy
    logout
    flash[:success] = "Вы успешно вышли из системы"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Регистрация прошла успешно"
      auto_login(@user)
      redirect_to root_path
    else
      flash.now[:fail] = "Неправильное имя или пароль"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_card.html.erb
<div class="card-item">
  <div class="review-date">Дата: <%= card.review_date.strftime("%d/%m/%Y") %></div>
  <%= image_tag card.image.url(:thumb) %>
  <%= link_to card.original_text, [@pack, card], class: "original-text", title: "Смотреть" %>
</div>

app/views/cards/_card_form.html.erb
<%= simple_form_for @card do |f| %>
  <%= f.input :original_text, placeholder: "Слово" %>
  <%= f.input :translated_text, placeholder: "Перевод" %>
  <%= f.button :submit, "Сохранить" %>
<% end %>

app/views/cards/_fail_check.html.erb
<p>Карт на сегодня больше нет!</p>

app/views/cards/_form.html.erb
<div class="edit-form">
  <%= simple_form_for [@pack, @card], html: { class: "form" } do |f| %>
    <%= f.input :original_text, placeholder: "Слово" %>
    <%= f.input :translated_text, placeholder: "Перевод" %>
    <%= f.button :submit, "Сохранить", class: "button" %>
  <% end %>
</div>

app/views/cards/_review_form.html.erb
<div class="review-date">Дата: <%= card.review_date.strftime "%d/%m/%Y" %></div>
<%= image_tag card.image.url %>
<div class="original-text"><%= card.original_text %></div>
<%= form_tag review_path, remote: true, class: "form review-form" do %>
  <%= text_field_tag "translated_text", nil, placeholder: "Перевод", class: "field" %>
  <%= hidden_field_tag "card_id", card.id %>
  <%= hidden_field_tag "answer_time", "1" %>
  <%= button_tag "Проверить", class: "button" %>
<% end %>

app/views/cards/edit.html.erb
<h2>Редактирование карты</h2>
<%= render "cards/form" %>

app/views/cards/get_card_for_review.js.erb
<% if @card %>
  $(".main-card-item").html("<%= escape_javascript(render 'review_form', card: @card) %>");
<% else %>
  $(".content").html("<p>Карт на сегодня больше нет!</p>");
<% end %>

app/views/cards/index.html.erb
<h1>Карты</h1>
<div class="cards-list">
  <% @cards.each do |card| %>
    <%= render card %>
  <% end %>
</div>

app/views/cards/new.html.erb
<h1>Создание флешкарты</h1>
<div class="edit-form">
  <%= simple_form_for [@pack, @card], html: { class: "form" } do |f| %>
    <%= f.input :original_text, placeholder: "Слово" %>
    <%= f.input :translated_text, placeholder: "Перевод" %>
    <%= f.input :image, as: :file %>
    <%= f.button :submit, "Сохранить", class: "button" %>
  <% end %>
</div>

app/views/cards/review.js.erb
$(".flash_area").html("<%= escape_javascript(render 'shared/notice', flash: flash) %>");
$(".review-form").on("ajax:success",
  function(){
    $.ajax({
      url: "<%= root_url %>"
    });
  }
);

app/views/cards/review_card.js.erb
$(".flash_area").html("<%= escape_javascript(render 'shared/notice', flash: flash) %>");
$(".review-form").on("ajax:success",
  function(){
    $.ajax({
      url: "<%= get_card_for_review_url %>"
    });
  }
);

app/views/cards/show.html.erb
<div class="card-item show-card">
  <div class="review-date">
    Дата: <%= @card.review_date.strftime("%d/%m/%Y") %>
  </div>
  <%= image_tag @card.image.url(:thumb) %>
  <div class="words-wrap">
    <%= @card.original_text %> | <%= @card.translated_text %>
  </div>
  <div class="card-item__links">
    <%= link_to "Редактировать", edit_pack_card_path, class: "button green", title: "Редактировать" %>
    <%= link_to "Удалить", [@pack, @card], method: :delete, class: "button red", title: "Удалить" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Флэшкарточкер</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<body>
  <div class="header clearfix">
    <div class="container">
      <a href="/" class="logo"><%= image_tag("logo.png", alt: "Флэшкарточкер") %><span>Флэшкарточкер</span></a>
      <div class="navigation-links user-nav">
        <% if current_user %>
          <%= link_to "Выход", logout_path %>
        <% else %>
          <%= link_to "Вход", login_path %> |
          <%= link_to "Регистрация", signup_path %>
        <% end %>
      </div>
      <% if current_user %>
        <div class="navigation-links">
          <%= link_to "Колоды", packs_path %>
          <%= link_to "Добавить колоду", new_pack_path %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="container">
    <div class="flash_area">
      <%= render "shared/notice", flash: flash %>
    </div>
    <div class="content">
      <%= yield %>
    </div>
    <%# debug(params) if Rails.env.development? %>
  </div>
</body>

</body>
</html>

app/views/packs/edit.html.erb
<h1>Редактирование колоды</h1>
<div class="edit-form">
  <%= simple_form_for @pack, html: { class: "form" } do |f| %>
    <%= f.input :title, placeholder: "Название колоды" %>
    <%= f.button :submit, "Сохранить", class: "button" %>
  <% end %>
</div>

app/views/packs/index.html.erb
<h1>Колоды</h1>
<div class="packs-list">
  <% @packs.each do |pack| %>
    <div class="pack-item<%= " current" if pack.current? %>">
      <%= image_tag pack.image.url %>
      <%= link_to pack.title, pack, class: "pack-item__title", title: "Смотреть" %>
    </div>
  <% end %>
</div>

app/views/packs/new.html.erb
<h1>Создание колоды</h1>
<div class="edit-form">
  <%= simple_form_for @pack, html: { class: "form" } do |f| %>
    <%= f.input :title, placeholder: "Название колоды" %>
    <%= f.input :image, as: :file %>
    <%= f.button :submit, "Сохранить", class: "button" %>
  <% end %>
</div>

app/views/packs/set_current_pack.js.erb
$(".pack-item").addClass("current");
$("#make-current-btn").hide();

app/views/packs/show.html.erb
<h1>Колода &laquo<%= @pack.title %>&raquo</h1>
<div class="pack-item<%= " current" if @pack.current? %>" id="pack-item<%= @pack.id %>">
  <%= image_tag @pack.image.url %>
  <div class="pack-buttons">
    <%= link_to "Редактировать", edit_pack_path, class: "button yellow", title: "Редактировать" %>
    <% if !@pack.current? %>
      <%= form_tag set_current_pack_path, remote: true, class: "form make-current" do |f| %>
        <%= hidden_field_tag :pack_id, @pack.id %>
        <%= button_tag "Сделать текущей", class: "button blue", id: "make-current-btn", title: "Сделать текущей" %>
      <% end %>
    <% end %>
    <%= link_to "Удалить", @pack, method: :delete, class: "button red", title: "Удалить" %>
    <%= link_to "Добавить карту", new_pack_card_path(@pack), class: "button green", title: "Добавить карту" %>
  </div>
</div>
<% if !@pack.cards.blank? %>
  <h2>Карты в колоде</h2>
  <div class="cards-list">
    <% @pack.cards.each do |card| %>
      <%= render card %>
    <% end %>
  </div>
<% end %>

app/views/review/review_card.js.erb
$(".flash_area").html("<%= escape_javascript(render 'shared/notice', flash: flash) %>");
$(".review-form").on("ajax:success",
  function(){
    $.ajax({
      url: "<%= root_url %>"
    });
  }
);

app/views/reviews/_form.html.erb
<div class="review-date">Дата: <%= card.review_date.strftime "%d/%m/%Y" %></div>
<%= image_tag card.image.url %>
<div class="original-text"><%= card.original_text %></div>
<%= form_tag review_path, remote: true, class: "form review-form" do %>
  <%= text_field_tag "translated_text", nil, placeholder: "Перевод", class: "field" %>
  <%= hidden_field_tag "card_id", card.id %>
  <%= hidden_field_tag "answer_time", "1" %>
  <%= button_tag "Проверить", class: "button" %>
<% end %>

app/views/reviews/create.js.erb
$(".flash_area").html("<%= escape_javascript(render 'shared/notice', flash: flash) %>");

app/views/shared/_notice.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}", id: "alert-#{key}") %>
<% end %>

app/views/static_pages/_check_card_form.html.erb
<div class="review-date">Дата: <%= card.review_date.strftime "%d/%m/%Y" %></div>
<%= image_tag card.image.url %>
<div class="original-text"><%= card.original_text %></div>
<%= form_tag review_card_path, remote: true, class: "form check-card-form" do %>
  <%= text_field_tag "translated_text", nil, placeholder: "Перевод", class: "field" %>
  <%= hidden_field_tag "card_id", card.id %>
  <%= hidden_field_tag "answer_time", "1" %>
  <%= button_tag "Проверить", class: "button" %>
<% end %>

app/views/static_pages/check_card.js.erb
$(".flash_area").html("<%= escape_javascript(render 'shared/notice', flash: flash) %>");
<% if @card %>
  $("#main-card-item").html("<%= escape_javascript(render 'check_card_form', card: @card) %>");
<% else %>
  $(".content").html("<p>Карт на сегодня больше нет!</p>");
<% end %>

app/views/static_pages/home.html.erb
<% if current_user %>
  <% if @card %>
    <div class="main-card-item">
      <%= render "reviews/form", card: @card %>
    </div>
  <% else %>
    <p>Карт на сегодня больше нет!</p>
  <% end %>
<% else %>
  <p>Войдите или зарегистрируйтесь</p>
<% end %>

app/views/static_pages/home.js.erb
<% if @card %>
  $(".main-card-item").html("<%= escape_javascript(render 'reviews/form', card: @card) %>");
<% else %>
  $(".content").html("<p>Карт на сегодня больше нет!</p>");
<% end %>

app/views/user_sessions/new.html.erb
<h1>Войти</h1>
<div class="edit-form">
  <%= form_tag user_sessions_path, class: "form" do %>
    <%= text_field_tag :email, nil, placeholder: "E-mail", class: "field"%>
    <%= password_field_tag :password, nil, placeholder: "Пароль", class: "field" %>
    <%= check_box_tag :remember_me, 1, params[:remember_me] %>
    <%= label_tag :remember_me, "Запомнить меня" %>
    <%= button_tag "Отправить", class: "button" %>
  <% end %>
  <%= link_to "Войти через Twitter", auth_at_provider_path(provider: :twitter) %>
</div>

app/views/users/new.html.erb
<h1>Регистрация</h1>
<div class="edit-form">
  <%= simple_form_for @user, html: { class: "form" } do |f| %>
    <%= f.input :email, placeholder: "E-mail" %>
    <%= f.input :password, placeholder: "Пароль" %>
    <%= f.input :password_confirmation, placeholder: "Подтвердите пароль" %>
    <%= f.button :submit, "Отправить", class: "button" %>
  <% end %>
</div>